window.MEAL_PLAN_DATA["mealPlan"] = [
  {
    "Day": "Day 1",
    "Meal / Timing": "Breakfast",
    "Exact Ingredients (1 item per line)": "Oats 45 g\nLow-fat milk 300 ml\nWhole eggs 1\nEgg whites 100 g\nMushrooms [CF] 100 g\nSEPARATE SEED SIDE:\nChia seeds 8 g\nGround flaxseed 7 g\nHemp hearts 5 g\nNo added salt; no onion/garlic in this milk-containing meal\nDo not mix seeds into the milk/grain bowl",
    "Calories (kcal)": 546,
    "Protein (g)": 40.6,
    "Carbs (g)": 55.7,
    "Fiber (g)": 10.4,
    "Fat (g)": 19,
    "Calcium (mg)": 508.3,
    "Iron (mg)": 4.9,
    "Magnesium (mg)": 210.4,
    "Potassium (mg)": 1312.4,
    "B12 (µg)": 1.9,
    "Vitamin D (µg)": 4.8,
    "Folate (µg DFE)": 100.2,
    "Omega-3 (g)": 3.7,
    "Viruddha-Ahara safeguard": "Milk kept away from fruit, meat/fish, added salt, onion and garlic; breakfast seed mix is eaten separately from the milk/grain bowl.",
    "Sat Fat (g)": 4.8,
    "Preformed Vitamin A (µg RAE)": 218
  },
  {
    "Day": "Day 1",
    "Meal / Timing": "Mid-morning fruit",
    "Exact Ingredients (1 item per line)": "Papaya [CF] 150 g\nEat alone; ≥2 h after breakfast and ≥2 h before lunch",
    "Calories (kcal)": 64.5,
    "Protein (g)": 0.8,
    "Carbs (g)": 16.2,
    "Fiber (g)": 2.5,
    "Fat (g)": 0.4,
    "Calcium (mg)": 30,
    "Iron (mg)": 0.4,
    "Magnesium (mg)": 31.5,
    "Potassium (mg)": 273,
    "B12 (µg)": 0,
    "Vitamin D (µg)": 0,
    "Folate (µg DFE)": 55.5,
    "Omega-3 (g)": 0,
    "Viruddha-Ahara safeguard": "Fruit eaten alone, separated from dairy and main meals.",
    "Sat Fat (g)": 0.12,
    "Preformed Vitamin A (µg RAE)": 0
  },
  {
    "Day": "Day 1",
    "Meal / Timing": "Lunch",
    "Exact Ingredients (1 item per line)": "Chicken breast 100 g\nICAN cod liver 20 g\nRice (dry) 45 g\nToor dal (dry) 35 g\nAsparagus [CF] 100 g\nCauliflower [CF] 150 g\nOnion [CF] 40 g\nSesame seeds 12 g\nCooking oil 3 g\nNo milk/curd/yogurt",
    "Calories (kcal)": 663.5,
    "Protein (g)": 42.6,
    "Carbs (g)": 76.3,
    "Fiber (g)": 13,
    "Fat (g)": 22,
    "Calcium (mg)": 246.3,
    "Iron (mg)": 7.1,
    "Magnesium (mg)": 185.9,
    "Potassium (mg)": 1638,
    "B12 (µg)": 0.3,
    "Vitamin D (µg)": 29.3,
    "Folate (µg DFE)": 323.9,
    "Omega-3 (g)": 0.7,
    "Viruddha-Ahara safeguard": "No dairy with non-veg; no fruit; no honey/ghee; dinner has no curd/yogurt.",
    "Sat Fat (g)": 5.39,
    "Preformed Vitamin A (µg RAE)": 1413.7
  },
  {
    "Day": "Day 1",
    "Meal / Timing": "Dinner",
    "Exact Ingredients (1 item per line)": "Chicken breast 100 g\nRice (dry) 40 g\nCabbage [CF] 150 g\nCarrots [CF] 100 g\nMushrooms [CF] 100 g\nFrozen sweet peas [CF] 60 g\nSesame seeds 10 g\nCooking oil 3 g\nNo milk/curd/yogurt",
    "Calories (kcal)": 498.9,
    "Protein (g)": 36.3,
    "Carbs (g)": 64.6,
    "Fiber (g)": 12.3,
    "Fat (g)": 11.7,
    "Calcium (mg)": 224.7,
    "Iron (mg)": 4.6,
    "Magnesium (mg)": 131.9,
    "Potassium (mg)": 1466.2,
    "B12 (µg)": 0.3,
    "Vitamin D (µg)": 0.3,
    "Folate (µg DFE)": 156.4,
    "Omega-3 (g)": 0.3,
    "Viruddha-Ahara safeguard": "No dairy with non-veg; no fruit; no honey/ghee; dinner has no curd/yogurt.",
    "Sat Fat (g)": 1.93,
    "Preformed Vitamin A (µg RAE)": 5
  },
  {
    "Day": "Day 2",
    "Meal / Timing": "Breakfast",
    "Exact Ingredients (1 item per line)": "Ragi flour 45 g\nLow-fat milk 300 ml\nWhole eggs 1\nEgg whites 50 g\nSEPARATE SEED SIDE:\nSesame seeds 5 g\nHemp hearts 5 g\nChia seeds 5 g\nNo added salt; no onion/garlic in this milk-containing meal\nDo not mix seeds into the milk/ragi bowl",
    "Calories (kcal)": 455.3,
    "Protein (g)": 28.5,
    "Carbs (g)": 51.9,
    "Fiber (g)": 7.7,
    "Fat (g)": 14.9,
    "Calcium (mg)": 645.1,
    "Iron (mg)": 4.3,
    "Magnesium (mg)": 175.4,
    "Potassium (mg)": 887.9,
    "B12 (µg)": 1.8,
    "Vitamin D (µg)": 4.6,
    "Folate (µg DFE)": 72.2,
    "Omega-3 (g)": 1.6,
    "Viruddha-Ahara safeguard": "Milk kept away from fruit, meat/fish, added salt, onion and garlic; breakfast seed mix is eaten separately from the milk/grain bowl.",
    "Sat Fat (g)": 4.33,
    "Preformed Vitamin A (µg RAE)": 218
  },
  {
    "Day": "Day 2",
    "Meal / Timing": "Mid-morning fruit",
    "Exact Ingredients (1 item per line)": "Kiwi [CF] 150 g\nEat alone; ≥2 h after breakfast and ≥2 h before lunch",
    "Calories (kcal)": 91.5,
    "Protein (g)": 1.7,
    "Carbs (g)": 22,
    "Fiber (g)": 4.5,
    "Fat (g)": 0.8,
    "Calcium (mg)": 51,
    "Iron (mg)": 0.5,
    "Magnesium (mg)": 25.5,
    "Potassium (mg)": 468,
    "B12 (µg)": 0,
    "Vitamin D (µg)": 0,
    "Folate (µg DFE)": 37.5,
    "Omega-3 (g)": 0.1,
    "Viruddha-Ahara safeguard": "Fruit eaten alone, separated from dairy and main meals.",
    "Sat Fat (g)": 0.04,
    "Preformed Vitamin A (µg RAE)": 0
  },
  {
    "Day": "Day 2",
    "Meal / Timing": "Lunch",
    "Exact Ingredients (1 item per line)": "Chicken breast 100 g\nRajma (dry) 45 g\nRice (dry) 40 g\nCabbage [CF] 150 g\nCauliflower [CF] 150 g\nOnion [CF] 50 g\nSesame seeds 10 g\nCooking oil 3 g\nNo milk/curd/yogurt",
    "Calories (kcal)": 594.7,
    "Protein (g)": 43.1,
    "Carbs (g)": 82.2,
    "Fiber (g)": 20.5,
    "Fat (g)": 11.9,
    "Calcium (mg)": 282.6,
    "Iron (mg)": 7.3,
    "Magnesium (mg)": 181.6,
    "Potassium (mg)": 1836,
    "B12 (µg)": 0.3,
    "Vitamin D (µg)": 0.1,
    "Folate (µg DFE)": 353.7,
    "Omega-3 (g)": 0.3,
    "Viruddha-Ahara safeguard": "No dairy with non-veg; no fruit; no honey/ghee; dinner has no curd/yogurt.",
    "Sat Fat (g)": 2.06,
    "Preformed Vitamin A (µg RAE)": 5
  },
  {
    "Day": "Day 2",
    "Meal / Timing": "Dinner",
    "Exact Ingredients (1 item per line)": "Whole eggs 2\nEgg whites 150 g\nMoong dal (dry) 40 g\nAsparagus [CF] 120 g\nMushrooms [CF] 150 g\nCarrots [CF] 100 g\nRice (dry) 35 g\nSesame seeds 10 g\nCooking oil 3 g\nNo milk/curd/yogurt",
    "Calories (kcal)": 669.4,
    "Protein (g)": 51,
    "Carbs (g)": 76.4,
    "Fiber (g)": 15,
    "Fat (g)": 19.3,
    "Calcium (mg)": 292.9,
    "Iron (mg)": 9.9,
    "Magnesium (mg)": 190.2,
    "Potassium (mg)": 2007.4,
    "B12 (µg)": 1.1,
    "Vitamin D (µg)": 2.3,
    "Folate (µg DFE)": 422.4,
    "Omega-3 (g)": 0.4,
    "Viruddha-Ahara safeguard": "No dairy with non-veg; no fruit; no honey/ghee; dinner has no curd/yogurt.",
    "Sat Fat (g)": 4.61,
    "Preformed Vitamin A (µg RAE)": 160
  },
  {
    "Day": "Day 3",
    "Meal / Timing": "Breakfast",
    "Exact Ingredients (1 item per line)": "Oats 37 g\nLow-fat milk 300 ml\nWhole eggs 2\nEgg whites 50 g\nSEPARATE SEED SIDE:\nChia seeds 5 g\nPumpkin seeds 5 g\nSunflower seeds 5 g\nNo added salt; no onion/garlic in this milk-containing meal\nDo not mix seeds into the milk/oats",
    "Calories (kcal)": 515.9,
    "Protein (g)": 36.2,
    "Carbs (g)": 44.8,
    "Fiber (g)": 6.2,
    "Fat (g)": 21.5,
    "Calcium (mg)": 491.3,
    "Iron (mg)": 4.5,
    "Magnesium (mg)": 161,
    "Potassium (mg)": 896.6,
    "B12 (µg)": 2.3,
    "Vitamin D (µg)": 5.6,
    "Folate (µg DFE)": 101.4,
    "Omega-3 (g)": 1.2,
    "Viruddha-Ahara safeguard": "Milk kept away from fruit, meat/fish, added salt, onion and garlic; breakfast seed mix is eaten separately from the milk/grain bowl.",
    "Sat Fat (g)": 6.29,
    "Preformed Vitamin A (µg RAE)": 298
  },
  {
    "Day": "Day 3",
    "Meal / Timing": "Mid-morning fruit",
    "Exact Ingredients (1 item per line)": "Pineapple [CF] 150 g\nEat alone; ≥2 h after breakfast and ≥2 h before lunch",
    "Calories (kcal)": 75,
    "Protein (g)": 0.8,
    "Carbs (g)": 19.6,
    "Fiber (g)": 2.1,
    "Fat (g)": 0.2,
    "Calcium (mg)": 19.5,
    "Iron (mg)": 0.4,
    "Magnesium (mg)": 18,
    "Potassium (mg)": 163.5,
    "B12 (µg)": 0,
    "Vitamin D (µg)": 0,
    "Folate (µg DFE)": 27,
    "Omega-3 (g)": 0,
    "Viruddha-Ahara safeguard": "Fruit eaten alone, separated from dairy and main meals.",
    "Sat Fat (g)": 0.01,
    "Preformed Vitamin A (µg RAE)": 0
  },
  {
    "Day": "Day 3",
    "Meal / Timing": "Lunch",
    "Exact Ingredients (1 item per line)": "Chicken breast 100 g\nMoong dal (dry) 35 g\nRice (dry) 35 g\nAsparagus [CF] 100 g\nCabbage [CF] 150 g\nCauliflower [CF] 100 g\nOnion [CF] 40 g\nSesame seeds 10 g\nCooking oil 2 g\nNo milk/curd/yogurt",
    "Calories (kcal)": 542.7,
    "Protein (g)": 41.6,
    "Carbs (g)": 73.6,
    "Fiber (g)": 15.9,
    "Fat (g)": 10.8,
    "Calcium (mg)": 273.7,
    "Iron (mg)": 7.8,
    "Magnesium (mg)": 189,
    "Potassium (mg)": 1671.5,
    "B12 (µg)": 0.3,
    "Vitamin D (µg)": 0.1,
    "Folate (µg DFE)": 416.4,
    "Omega-3 (g)": 0.5,
    "Viruddha-Ahara safeguard": "No dairy with non-veg; no fruit; no honey/ghee; dinner has no curd/yogurt.",
    "Sat Fat (g)": 1.95,
    "Preformed Vitamin A (µg RAE)": 5
  },
  {
    "Day": "Day 3",
    "Meal / Timing": "Dinner",
    "Exact Ingredients (1 item per line)": "Whole eggs 1\nEgg whites 150 g\nChickpeas (dry) 40 g\nRagi flour 45 g\nMushrooms [CF] 150 g\nCabbage [CF] 150 g\nFrozen sweet peas [CF] 60 g\nSesame seeds 10 g\nCooking oil 2 g\nNo milk/curd/yogurt",
    "Calories (kcal)": 646,
    "Protein (g)": 45.7,
    "Carbs (g)": 83.7,
    "Fiber (g)": 19.5,
    "Fat (g)": 15.8,
    "Calcium (mg)": 393.1,
    "Iron (mg)": 8.3,
    "Magnesium (mg)": 202.2,
    "Potassium (mg)": 1709.5,
    "B12 (µg)": 0.6,
    "Vitamin D (µg)": 1.3,
    "Folate (µg DFE)": 409.9,
    "Omega-3 (g)": 0.3,
    "Viruddha-Ahara safeguard": "No dairy with non-veg; no fruit; no honey/ghee; dinner has no curd/yogurt.",
    "Sat Fat (g)": 3.08,
    "Preformed Vitamin A (µg RAE)": 80
  },
  {
    "Day": "Day 4",
    "Meal / Timing": "Breakfast",
    "Exact Ingredients (1 item per line)": "Oats 37 g\nLow-fat milk 300 ml\nWhole eggs 1\nEgg whites 50 g\nSEPARATE SEED SIDE:\nGround flaxseed 5 g\nHemp hearts 5 g\nSunflower seeds 5 g\nNo added salt; no onion/garlic in this milk-containing meal\nDo not mix seeds into the milk/oats",
    "Calories (kcal)": 446.5,
    "Protein (g)": 30,
    "Carbs (g)": 43.8,
    "Fiber (g)": 5.7,
    "Fat (g)": 17.3,
    "Calcium (mg)": 445.7,
    "Iron (mg)": 3.5,
    "Magnesium (mg)": 163.3,
    "Potassium (mg)": 862,
    "B12 (µg)": 1.8,
    "Vitamin D (µg)": 4.6,
    "Folate (µg DFE)": 82.4,
    "Omega-3 (g)": 1.8,
    "Viruddha-Ahara safeguard": "Milk kept away from fruit, meat/fish, added salt, onion and garlic; breakfast seed mix is eaten separately from the milk/grain bowl.",
    "Sat Fat (g)": 4.54,
    "Preformed Vitamin A (µg RAE)": 218
  },
  {
    "Day": "Day 4",
    "Meal / Timing": "Mid-morning fruit",
    "Exact Ingredients (1 item per line)": "Mango [CF] 150 g\nEat alone; ≥2 h after breakfast and ≥2 h before lunch",
    "Calories (kcal)": 90,
    "Protein (g)": 1.2,
    "Carbs (g)": 22.5,
    "Fiber (g)": 2.4,
    "Fat (g)": 0.6,
    "Calcium (mg)": 16.5,
    "Iron (mg)": 0.2,
    "Magnesium (mg)": 15,
    "Potassium (mg)": 252,
    "B12 (µg)": 0,
    "Vitamin D (µg)": 0,
    "Folate (µg DFE)": 64.5,
    "Omega-3 (g)": 0.1,
    "Viruddha-Ahara safeguard": "Fruit eaten alone, separated from dairy and main meals.",
    "Sat Fat (g)": 0.14,
    "Preformed Vitamin A (µg RAE)": 0
  }
];