window.MEAL_PLAN_DATA["mealPlan"].push(...[
  {
    "Day": "Day 4",
    "Meal / Timing": "Lunch",
    "Exact Ingredients (1 item per line)": "Tilapia fillet 160 g\nChickpeas (dry) 40 g\nRice (dry) 40 g\nAsparagus [CF] 120 g\nCauliflower [CF] 150 g\nCarrots [CF] 100 g\nOnion [CF] 40 g\nSesame seeds 15 g\nCooking oil 3 g\nNo milk/curd/yogurt",
    "Calories (kcal)": 681.8,
    "Protein (g)": 52.7,
    "Carbs (g)": 86.2,
    "Fiber (g)": 16.2,
    "Fat (g)": 16.7,
    "Calcium (mg)": 300.2,
    "Iron (mg)": 8.7,
    "Magnesium (mg)": 192.8,
    "Potassium (mg)": 1955.9,
    "B12 (µg)": 2.6,
    "Vitamin D (µg)": 5,
    "Folate (µg DFE)": 453.5,
    "Omega-3 (g)": 0.6,
    "Viruddha-Ahara safeguard": "No dairy with non-veg; no fruit; no honey/ghee; dinner has no curd/yogurt.",
    "Sat Fat (g)": 3.02,
    "Preformed Vitamin A (µg RAE)": 0
  },
  {
    "Day": "Day 4",
    "Meal / Timing": "Dinner",
    "Exact Ingredients (1 item per line)": "Chicken breast 100 g\nMoong dal (dry) 35 g\nRice (dry) 40 g\nCabbage [CF] 150 g\nMushrooms [CF] 150 g\nFrozen sweet peas [CF] 60 g\nSesame seeds 10 g\nCooking oil 3 g\nNo milk/curd/yogurt",
    "Calories (kcal)": 590.4,
    "Protein (g)": 45.3,
    "Carbs (g)": 78.6,
    "Fiber (g)": 15.7,
    "Fat (g)": 12.1,
    "Calcium (mg)": 239.4,
    "Iron (mg)": 6.9,
    "Magnesium (mg)": 190.5,
    "Potassium (mg)": 1741.3,
    "B12 (µg)": 0.4,
    "Vitamin D (µg)": 0.4,
    "Folate (µg DFE)": 364.6,
    "Omega-3 (g)": 0.4,
    "Viruddha-Ahara safeguard": "No dairy with non-veg; no fruit; no honey/ghee; dinner has no curd/yogurt.",
    "Sat Fat (g)": 2.03,
    "Preformed Vitamin A (µg RAE)": 5
  },
  {
    "Day": "Day 5",
    "Meal / Timing": "Breakfast",
    "Exact Ingredients (1 item per line)": "Ragi flour 45 g\nLow-fat milk 300 ml\nWhole eggs 1\nEgg whites 50 g\nSEPARATE SEED SIDE:\nSesame seeds 5 g\nSunflower seeds 5 g\nChia seeds 5 g\nNo added salt; no onion/garlic in this milk-containing meal\nDo not mix seeds into the milk/ragi bowl",
    "Calories (kcal)": 456.9,
    "Protein (g)": 28,
    "Carbs (g)": 52.4,
    "Fiber (g)": 8,
    "Fat (g)": 15,
    "Calcium (mg)": 645.6,
    "Iron (mg)": 4.1,
    "Magnesium (mg)": 156.7,
    "Potassium (mg)": 860.2,
    "B12 (µg)": 1.8,
    "Vitamin D (µg)": 4.6,
    "Folate (µg DFE)": 78.1,
    "Omega-3 (g)": 1.1,
    "Viruddha-Ahara safeguard": "Milk kept away from fruit, meat/fish, added salt, onion and garlic; breakfast seed mix is eaten separately from the milk/grain bowl.",
    "Sat Fat (g)": 4.33,
    "Preformed Vitamin A (µg RAE)": 218
  },
  {
    "Day": "Day 5",
    "Meal / Timing": "Mid-morning fruit",
    "Exact Ingredients (1 item per line)": "Papaya [CF] 150 g\nEat alone; ≥2 h after breakfast and ≥2 h before lunch",
    "Calories (kcal)": 64.5,
    "Protein (g)": 0.8,
    "Carbs (g)": 16.2,
    "Fiber (g)": 2.5,
    "Fat (g)": 0.4,
    "Calcium (mg)": 30,
    "Iron (mg)": 0.4,
    "Magnesium (mg)": 31.5,
    "Potassium (mg)": 273,
    "B12 (µg)": 0,
    "Vitamin D (µg)": 0,
    "Folate (µg DFE)": 55.5,
    "Omega-3 (g)": 0,
    "Viruddha-Ahara safeguard": "Fruit eaten alone, separated from dairy and main meals.",
    "Sat Fat (g)": 0.12,
    "Preformed Vitamin A (µg RAE)": 0
  },
  {
    "Day": "Day 5",
    "Meal / Timing": "Lunch",
    "Exact Ingredients (1 item per line)": "Chicken breast 100 g\nMasoor dal (dry) 40 g\nRice (dry) 35 g\nCauliflower [CF] 150 g\nCabbage [CF] 150 g\nCarrots [CF] 100 g\nOnion [CF] 40 g\nSesame seeds 10 g\nCooking oil 3 g\nNo milk/curd/yogurt",
    "Calories (kcal)": 604.4,
    "Protein (g)": 42.7,
    "Carbs (g)": 85.2,
    "Fiber (g)": 16.1,
    "Fat (g)": 12.1,
    "Calcium (mg)": 261.5,
    "Iron (mg)": 6.4,
    "Magnesium (mg)": 147.2,
    "Potassium (mg)": 1773.8,
    "B12 (µg)": 0.3,
    "Vitamin D (µg)": 0.1,
    "Folate (µg DFE)": 384.7,
    "Omega-3 (g)": 0.3,
    "Viruddha-Ahara safeguard": "No dairy with non-veg; no fruit; no honey/ghee; dinner has no curd/yogurt.",
    "Sat Fat (g)": 2.1,
    "Preformed Vitamin A (µg RAE)": 5
  },
  {
    "Day": "Day 5",
    "Meal / Timing": "Dinner",
    "Exact Ingredients (1 item per line)": "Whole eggs 2\nEgg whites 150 g\nRajma (dry) 40 g\nAsparagus [CF] 120 g\nMushrooms [CF] 150 g\nFrozen sweet peas [CF] 60 g\nRice (dry) 30 g\nSesame seeds 10 g\nCooking oil 3 g\nNo milk/curd/yogurt",
    "Calories (kcal)": 653.1,
    "Protein (g)": 52.8,
    "Carbs (g)": 70.4,
    "Fiber (g)": 18.6,
    "Fat (g)": 19.1,
    "Calcium (mg)": 277.9,
    "Iron (mg)": 11,
    "Magnesium (mg)": 177.2,
    "Potassium (mg)": 1892,
    "B12 (µg)": 1.1,
    "Vitamin D (µg)": 2.3,
    "Folate (µg DFE)": 349.6,
    "Omega-3 (g)": 0.4,
    "Viruddha-Ahara safeguard": "No dairy with non-veg; no fruit; no honey/ghee; dinner has no curd/yogurt.",
    "Sat Fat (g)": 4.51,
    "Preformed Vitamin A (µg RAE)": 160
  },
  {
    "Day": "Day 6",
    "Meal / Timing": "Breakfast",
    "Exact Ingredients (1 item per line)": "Oats 37 g\nLow-fat milk 300 ml\nWhole eggs 2\nSEPARATE SEED SIDE:\nChia seeds 5 g\nHemp hearts 5 g\nPumpkin seeds 5 g\nNo added salt; no onion/garlic in this milk-containing meal\nDo not mix seeds into the milk/oats",
    "Calories (kcal)": 488.4,
    "Protein (g)": 31.3,
    "Carbs (g)": 44,
    "Fiber (g)": 5.9,
    "Fat (g)": 21.3,
    "Calcium (mg)": 487.4,
    "Iron (mg)": 4.6,
    "Magnesium (mg)": 174.3,
    "Potassium (mg)": 842.9,
    "B12 (µg)": 2.2,
    "Vitamin D (µg)": 5.6,
    "Folate (µg DFE)": 93.6,
    "Omega-3 (g)": 1.6,
    "Viruddha-Ahara safeguard": "Milk kept away from fruit, meat/fish, added salt, onion and garlic; breakfast seed mix is eaten separately from the milk/grain bowl.",
    "Sat Fat (g)": 6.3,
    "Preformed Vitamin A (µg RAE)": 298
  },
  {
    "Day": "Day 6",
    "Meal / Timing": "Mid-morning fruit",
    "Exact Ingredients (1 item per line)": "Kiwi [CF] 150 g\nEat alone; ≥2 h after breakfast and ≥2 h before lunch",
    "Calories (kcal)": 91.5,
    "Protein (g)": 1.7,
    "Carbs (g)": 22,
    "Fiber (g)": 4.5,
    "Fat (g)": 0.8,
    "Calcium (mg)": 51,
    "Iron (mg)": 0.5,
    "Magnesium (mg)": 25.5,
    "Potassium (mg)": 468,
    "B12 (µg)": 0,
    "Vitamin D (µg)": 0,
    "Folate (µg DFE)": 37.5,
    "Omega-3 (g)": 0.1,
    "Viruddha-Ahara safeguard": "Fruit eaten alone, separated from dairy and main meals.",
    "Sat Fat (g)": 0.04,
    "Preformed Vitamin A (µg RAE)": 0
  },
  {
    "Day": "Day 6",
    "Meal / Timing": "Lunch",
    "Exact Ingredients (1 item per line)": "Chicken breast 100 g\nChickpeas (dry) 40 g\nRice (dry) 30 g\nCabbage [CF] 150 g\nCauliflower [CF] 150 g\nOnion [CF] 50 g\nSesame seeds 10 g\nCooking oil 2 g\nNo milk/curd/yogurt",
    "Calories (kcal)": 550.7,
    "Protein (g)": 40,
    "Carbs (g)": 72.4,
    "Fiber (g)": 14,
    "Fat (g)": 12.8,
    "Calcium (mg)": 238.2,
    "Iron (mg)": 5.2,
    "Magnesium (mg)": 147.7,
    "Potassium (mg)": 1479,
    "B12 (µg)": 0.3,
    "Vitamin D (µg)": 0.1,
    "Folate (µg DFE)": 398.4,
    "Omega-3 (g)": 0.3,
    "Viruddha-Ahara safeguard": "No dairy with non-veg; no fruit; no honey/ghee; dinner has no curd/yogurt.",
    "Sat Fat (g)": 2.09,
    "Preformed Vitamin A (µg RAE)": 5
  },
  {
    "Day": "Day 6",
    "Meal / Timing": "Dinner",
    "Exact Ingredients (1 item per line)": "Ocean perch fillet 160 g\nMoong dal (dry) 35 g\nRagi flour 45 g\nAsparagus [CF] 120 g\nMushrooms [CF] 150 g\nCarrots [CF] 100 g\nSesame seeds 15 g\nCooking oil 2 g\nNo milk/curd/yogurt",
    "Calories (kcal)": 619.9,
    "Protein (g)": 53.5,
    "Carbs (g)": 77.1,
    "Fiber (g)": 19.5,
    "Fat (g)": 13.2,
    "Calcium (mg)": 541.5,
    "Iron (mg)": 11.3,
    "Magnesium (mg)": 270.8,
    "Potassium (mg)": 2159.7,
    "B12 (µg)": 3.3,
    "Vitamin D (µg)": 4.3,
    "Folate (µg DFE)": 378.3,
    "Omega-3 (g)": 0.8,
    "Viruddha-Ahara safeguard": "No dairy with non-veg; no fruit; no honey/ghee; dinner has no curd/yogurt.",
    "Sat Fat (g)": 2.21,
    "Preformed Vitamin A (µg RAE)": 4.8
  },
  {
    "Day": "Day 7",
    "Meal / Timing": "Breakfast",
    "Exact Ingredients (1 item per line)": "Oats 38 g\nLow-fat milk 300 ml\nWhole eggs 1\nEgg whites 100 g\nSEPARATE SEED SIDE:\nGround flaxseed 5 g\nChia seeds 5 g\nSunflower seeds 5 g\nNo added salt; no onion/garlic in this milk-containing meal\nDo not mix seeds into the milk/oats",
    "Calories (kcal)": 473.1,
    "Protein (g)": 35,
    "Carbs (g)": 46.4,
    "Fiber (g)": 7.3,
    "Fat (g)": 16.6,
    "Calcium (mg)": 477.8,
    "Iron (mg)": 3.5,
    "Magnesium (mg)": 152.3,
    "Potassium (mg)": 908.1,
    "B12 (µg)": 1.9,
    "Vitamin D (µg)": 4.6,
    "Folate (µg DFE)": 81.9,
    "Omega-3 (g)": 2.2,
    "Viruddha-Ahara safeguard": "Milk kept away from fruit, meat/fish, added salt, onion and garlic; breakfast seed mix is eaten separately from the milk/grain bowl.",
    "Sat Fat (g)": 4.49,
    "Preformed Vitamin A (µg RAE)": 218
  },
  {
    "Day": "Day 7",
    "Meal / Timing": "Mid-morning fruit",
    "Exact Ingredients (1 item per line)": "Banana [CF] 120 g\nEat alone; ≥2 h after breakfast and ≥2 h before lunch",
    "Calories (kcal)": 106.8,
    "Protein (g)": 1.3,
    "Carbs (g)": 27.4,
    "Fiber (g)": 3.1,
    "Fat (g)": 0.4,
    "Calcium (mg)": 6,
    "Iron (mg)": 0.3,
    "Magnesium (mg)": 32.4,
    "Potassium (mg)": 429.6,
    "B12 (µg)": 0,
    "Vitamin D (µg)": 0,
    "Folate (µg DFE)": 24,
    "Omega-3 (g)": 0,
    "Viruddha-Ahara safeguard": "Fruit eaten alone, separated from dairy and main meals.",
    "Sat Fat (g)": 0.13,
    "Preformed Vitamin A (µg RAE)": 0
  },
  {
    "Day": "Day 7",
    "Meal / Timing": "Lunch",
    "Exact Ingredients (1 item per line)": "Lean goat/mutton 100 g\nMasoor dal (dry) 35 g\nRice (dry) 40 g\nAsparagus [CF] 100 g\nCabbage [CF] 150 g\nCauliflower [CF] 100 g\nOnion [CF] 50 g\nSesame seeds 10 g\nCooking oil 3 g\nNo milk/curd/yogurt",
    "Calories (kcal)": 564.5,
    "Protein (g)": 40.4,
    "Carbs (g)": 78.8,
    "Fiber (g)": 14.1,
    "Fat (g)": 11.5,
    "Calcium (mg)": 251.4,
    "Iron (mg)": 10.2,
    "Magnesium (mg)": 133.6,
    "Potassium (mg)": 1543.8,
    "B12 (µg)": 1.1,
    "Vitamin D (µg)": 0,
    "Folate (µg DFE)": 368.5,
    "Omega-3 (g)": 0.5,
    "Viruddha-Ahara safeguard": "No dairy with non-veg; no fruit; no honey/ghee; dinner has no curd/yogurt.",
    "Sat Fat (g)": 2.19,
    "Preformed Vitamin A (µg RAE)": 0
  },
  {
    "Day": "Day 7",
    "Meal / Timing": "Dinner",
    "Exact Ingredients (1 item per line)": "Chicken breast 100 g\nToor dal (dry) 35 g\nRice (dry) 35 g\nCauliflower [CF] 150 g\nCabbage [CF] 150 g\nMushrooms [CF] 100 g\nFrozen sweet peas [CF] 60 g\nSesame seeds 12 g\nCooking oil 3 g\nNo milk/curd/yogurt",
    "Calories (kcal)": 608.7,
    "Protein (g)": 45.8,
    "Carbs (g)": 81,
    "Fiber (g)": 17.9,
    "Fat (g)": 13.5,
    "Calcium (mg)": 288.3,
    "Iron (mg)": 7,
    "Magnesium (mg)": 212.2,
    "Potassium (mg)": 2085.5,
    "B12 (µg)": 0.3,
    "Vitamin D (µg)": 0.3,
    "Folate (µg DFE)": 384,
    "Omega-3 (g)": 0.4,
    "Viruddha-Ahara safeguard": "No dairy with non-veg; no fruit; no honey/ghee; dinner has no curd/yogurt.",
    "Sat Fat (g)": 2.33,
    "Preformed Vitamin A (µg RAE)": 5
  }
]);